port: 65000
hostname: localhost
logLevel: INFO
scribe_logger:
  use: false
  version: 3
proxies: proxyRU.txt
max-memory: 2000
aspiration:
  interactive: false
tests:
  default: local
  environments:
    local:
      port: 65000
      hostname: localhost
      use_auth: true
      service_location:
      autorun_server: false
      timeout: 5000
      silent: true
    ProductOnline:
      port: 12000
      hostname: localhost
      use_auth: true
      service_location: /CollectOnline
      autorun_server: false
      timeout: 5000
      silent: true
