default:
  server:
    port: 65000
    hostname: localhost
    use_auth: true
    service_location: ""
    autorun_server: false
    timeout: 5000
    silent: true
    credentials:
      user: user1
      password: pwd
  batchs:
    parallel: 6
    checking-interval: 2000
    max-checking: 9999
    input-file: batch.json
#    pre-processing:
#      cwd: 'ls'
#      arguements:
#        - value: -la
#        - value: /usr
    post-processing:
      cwd: '/home/collect/CsvToXls/install/jdk1.8.0/bin/java'
      arguements:
        - value: -Dcsvtoxls-config.properties=/home/collect/CsvToXls/apps/CsvToXls.properties
        - value: -Duser.timezone=Europe/Paris
        - value: -jar
        - value: /home/collect/CsvToXls/apps/CsvToXls-1.0-SNAPSHOT-standalone.jar
database:
    type          : oracle
    user          : LNK_BRICODEPOT
    password      : LNK_BRICODEPOT
    connectString : 192.168.1.129/RECETTE
    master        : BricoDepot
    poolMax       : 2
    poolMin       : 1
    poolIncrement : 1
    poolTimeout   : 4
