default:
  logger:
    appenders:
      - type: file
        filename: logs/batchs.log
        maxLogSize: 300000
        backups: 3
        level: INFO
      - out:
        type: console
        layout:
          type: basic
    categories:
      default:
        appenders: ['out']
        level: error
  server:
    port: 65000
    hostname: localhost
    use_auth: true
    service_location: ""
    autorun_server: false
    timeout: 5000
    silent: true
    credentials:
      user: user1
      password: pwd
  batchs:
    parallel: 6
    checking-interval: 2000
    max-checking: 9999
    input-file: batch.json
    pre-processing:
      cwd: 'ls'
      arguements:
        - value: -la
        - value: /usr
    post-processing:
      cwd: 'ls'
      arguements:
        - value: -la
        - value: /usr
database:
    type          : oracle
    user          : LNK_BRICODEPOT
    password      : LNK_BRICODEPOT
    connectString : 192.168.1.129/RECETTE
    master        : BricoDepot
    poolMax       : 2
    poolMin       : 1
    poolIncrement : 1
    poolTimeout   : 4
