default:
  liste_proxy: /home/svandecappelle/git/CollectOnline/proxyRU.txt
  nombres_requetes_paralleles: 50
  nb_clients_par_mag: 1
  mag_parrallele: 1
  minimum_msec_entre_mag: 500
  auto_exit: false
  writeCSV: false
  maxtry: 2
