WITH ALL_PRODUCTS AS (
	SELECT ID_PRODUIT, ENSEIGNE, LIEN_FICHEPRODUIT FROM (
	    SELECT ID AS ID_PRODUIT, 'BricoDepot' AS ENSEIGNE, LIEN_FICHEPRODUIT FROM PRODUIT
	    	UNION ALL
	    SELECT ID AS ID_PRODUIT, ENSEIGNE_CONC.LIBELLE, LIEN_FICHEPRODUIT FROM PRODUIT_EXT INNER JOIN ENSEIGNE_CONC ON ENSEIGNE_CONC.CODE = PRODUIT_EXT.CODE_ENS_CONC
	)
), LOGIQUES AS (
	SELECT ID_PRODUIT_MAITRE, ID_PRODUIT_MAITRE AS ID_PRODUIT, ID AS ID_LOGIQUE, 0 AS IS_EXTERN, 'BricoDepot' AS ENSEIGNE FROM LOGIQUE_H WHERE ID_PRODUIT_MAITRE IS NOT NULL
		UNION ALL
	SELECT LOGIQUE_H.ID_PRODUIT_MAITRE, ID_PRODUIT_EXT AS ID_PRODUIT, ID_LOGIQUE, 1, ENSEIGNE_CONC.LIBELLE AS ENSEIGNE FROM LOGIQUE_H_DETAILS
		INNER JOIN LOGIQUE_H ON LOGIQUE_H.ID = LOGIQUE_H_DETAILS.ID_LOGIQUE
		INNER JOIN PRODUIT_EXT ON LOGIQUE_H_DETAILS.ID_PRODUIT_EXT = PRODUIT_EXT.ID
		INNER JOIN ENSEIGNE_CONC ON PRODUIT_EXT.CODE_ENS_CONC = ENSEIGNE_CONC.CODE
	WHERE FLAG_FILS = 1
)
SELECT DISTINCT ALL_PRODUCTS.ID_PRODUIT, SHOPS.ENSEIGNE, ALL_PRODUCTS.LIEN_FICHEPRODUIT, LOGIQUES.ID_LOGIQUE  FROM LOGIQUES
INNER JOIN ALL_PRODUCTS ON ALL_PRODUCTS.ID_PRODUIT = LOGIQUES.ID_PRODUIT AND ALL_PRODUCTS.ENSEIGNE = LOGIQUES.ENSEIGNE
INNER JOIN (
	SELECT MAGASIN.CODE AS CODE_MAGASIN, ENSEIGNE.LIBELLE AS ENSEIGNE
		FROM MAGASIN, ENSEIGNE
	UNION ALL
		SELECT MAGASIN_CONC.CODE, ENSEIGNE_CONC.LIBELLE FROM MAGASIN_CONC, ENSEIGNE_CONC WHERE MAGASIN_CONC.CODE_ENSEIGNE_CONC = ENSEIGNE_CONC.CODE
	) SHOPS ON ALL_PRODUCTS.ENSEIGNE = SHOPS.ENSEIGNE
WHERE LOGIQUES.ID_PRODUIT_MAITRE IN (SELECT DISTINCT(ID_PRODUIT) FROM PRC_BD.DETAIL_COLLECT)
ORDER BY 1, 2, 3
