port: 65000
hostname: localhost
logLevel: DEBUG
scribe_logger:
  use: false
  version: 3
proxies: ../proxies.txt
max-memory: 2000
crawler:
  interactive: false
  export: true
  timeout: 10
tests:
  default: local
  environments:
    local:
      port: 65000
      hostname: localhost
      use_auth: true
      service_location:
      autorun_server: false
      timeout: 5000
      silent: true
    production:
      port: 12000
      hostname: localhost
      use_auth: true
      service_location: /straw-manager
      autorun_server: false
      timeout: 5000
      silent: true
