default:
  appenders:
    console:
      type: console
      level: DEBUG
    file:
      type: file
      filename: logs/output.log
      maxLogSize: 100000000
      backups: 10
    error-file:
      type: file
      filename: logs/error.log
      maxLogSize: 100000000
      backups: 10
    just-errors:
      type: logLevelFilter
      appender: error-file
      level: ERROR
  categories:
    default:
      level: INFO
      appenders:
        - console
        - file
        - just-errors