default:
  appenders:
    console:
      type: console
      level: INFO
    file:
      type: file
      filename: logs/output.log
      maxLogSize: 100000000
      backups: 10
    bricodepot:
      type: file
      filename: logs/sites/bricodepot.log
      maxLogSize: 100000000
      backups: 3
    bricoman:
      type: file
      filename: logs/sites/bricodepot.log
      maxLogSize: 100000000
      backups: 3
    bricomarche:
      type: file
      filename: logs/sites/bricomarche.log
      maxLogSize: 100000000
      backups: 3
    bricorama:
      type: file
      filename: logs/sites/bricorama.log
      maxLogSize: 100000000
      backups: 3
    castorama:
      type: file
      filename: logs/sites/castorama.log
      maxLogSize: 100000000
      backups: 3
    leroymerlin:
      type: file
      filename: logs/sites/leroymerlin.log
      maxLogSize: 100000000
      backups: 3
    mrbricolage:
      type: file
      filename: logs/sites/mrbricolage.log
      maxLogSize: 100000000
      backups: 3
    weldom:
      type: file
      filename: logs/sites/weldom.log
      maxLogSize: 100000000
      backups: 3
  categories:
    default:
      level: INFO
      appenders:
        - console
        - file
    BricoDepot:
      level: INFO
      appenders:
        - console
        - bricodepot
    Bricoman:
      level: INFO
      appenders:
        - console
        - bricoman
    Bricomarche:
      level: INFO
      appenders:
        - console
        - bricomarche
    Bricorama:
      level: INFO
      appenders:
        - console
        - bricorama
    Castorama:
      level: INFO
      appenders:
        - console
        - castorama
    LeroyMerlin:
      level: INFO
      appenders:
        - console
        - leroymerlin
    MrBricolage:
      level: INFO
      appenders:
        - console
        - mrbricolage
    Weldom:
      level: INFO
      appenders:
        - console
        - weldom
